name: tests
on:
  push:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: checkout
        uses: actions/checkout@v2

      - name: Install node_modules
        run: |
          npm ci

      - name: Run Jest tests
        run: |
          npm run nx test

      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run e2e:ci
          install: false
          headless: true

      - name: Run component tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run e2e:component:ci
          install: false
          headless: true

      - name: Run storybook tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run e2e:storybook:ci
          install: false
          headless: true

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress_artifacts
          path: |
            ${{ github.workspace }}/dist/cypress/apps/**/*.png
            ${{ github.workspace }}/dist/cypress/apps/**/*.mp4
